dist: xenial  
language: cpp
git:
  depth: false
matrix:
  include:
    - name: Linux GCC
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
        sonarcloud:
          organization: "elnormous-github"
          token:
            secure: "bWtYtCgUHIDTEPvAhsCvnB2oB2QHMlnh1ERBGGL1OjaHHHAn4NUNNUzWMOD7UGjiYRA6wXMbgiY1098VhOb4gDNFT8eKs5ND91mNl9FwNZMQzWiZSDfd5Y3ZMD4cNfzIlQ8eXJTkM8zRfBoGkoUF2CaUr9OAIck0hL7m3eNIxcyOcgsyqzdFxKeiBa8+nnwSlsdCxihjs3GvnKg+f+uW2qfjJaYiJjybu8Js4lO6coe4dG23Mn6kZ6r4v16JOpc8STYaAZGau9tvTHRsaVPQ23/Ynvk+iFHFZIoaBKt4qHPMb/xGnxMYqDdV7uixI2ZXOlg9qpwHN5lyE7Ms+8CjujJhW4+jOuWEwbpv5ASWjHHPn0BYyQmHefe38HnBoYEBevSUJDD7MMepAhy8DNh0YLIGBQCZ87qXk+qH1XtQdw6r24mDhCalODPzzr8q/A8Ca8SYoHwUU1xf1p+wktYB2i8c0Gr7JkFcKS/qL/2wMo27K4YMgoS5SOwe47tYwCull2bqvB2yKEgm3oZu6Kyt3PnvO8KcNObGIG+v8t+c3Loopv5TIJMItgjD2vK/qZUsFXCaD3r5wiOVPjju9j7yzz7DpJFHMMsjdnznN7EMRsJPz6p+lsfsMPxF4mabEG3hTr3FRCgtp0B9RkN/yC1tFe+ulshGTTXouYgppr3Teqo="
      before_install:
        - curl --insecure https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.3.0.2102-linux.zip -o sonar-scanner-cli-4.3.0.2102-linux.zip
        - unzip sonar-scanner-cli-4.3.0.2102-linux.zip -d ${TRAVIS_HOME}/.sonarscanner/
        - export PATH=${TRAVIS_HOME}/.sonarscanner/sonar-scanner-4.3.0.2102-linux/bin:$PATH
      before_script:
        - export CXX=g++-7
      script:
        - build-wrapper-linux-x86-64 --out-dir bw-output make -j2 -C samples/
        - sonar-scanner -D sonar.projectKey=HTTPRequestLinux -D sonar.projectName="HTTPRequest Linux" -D sonar.cfamily.threads=2 || true
    - name: macOS
      compiler: clang
      os: osx
      osx_image: xcode10
      addons:
        sonarcloud:
          organization: "elnormous-github"
          token:
            secure: "bWtYtCgUHIDTEPvAhsCvnB2oB2QHMlnh1ERBGGL1OjaHHHAn4NUNNUzWMOD7UGjiYRA6wXMbgiY1098VhOb4gDNFT8eKs5ND91mNl9FwNZMQzWiZSDfd5Y3ZMD4cNfzIlQ8eXJTkM8zRfBoGkoUF2CaUr9OAIck0hL7m3eNIxcyOcgsyqzdFxKeiBa8+nnwSlsdCxihjs3GvnKg+f+uW2qfjJaYiJjybu8Js4lO6coe4dG23Mn6kZ6r4v16JOpc8STYaAZGau9tvTHRsaVPQ23/Ynvk+iFHFZIoaBKt4qHPMb/xGnxMYqDdV7uixI2ZXOlg9qpwHN5lyE7Ms+8CjujJhW4+jOuWEwbpv5ASWjHHPn0BYyQmHefe38HnBoYEBevSUJDD7MMepAhy8DNh0YLIGBQCZ87qXk+qH1XtQdw6r24mDhCalODPzzr8q/A8Ca8SYoHwUU1xf1p+wktYB2i8c0Gr7JkFcKS/qL/2wMo27K4YMgoS5SOwe47tYwCull2bqvB2yKEgm3oZu6Kyt3PnvO8KcNObGIG+v8t+c3Loopv5TIJMItgjD2vK/qZUsFXCaD3r5wiOVPjju9j7yzz7DpJFHMMsjdnznN7EMRsJPz6p+lsfsMPxF4mabEG3hTr3FRCgtp0B9RkN/yC1tFe+ulshGTTXouYgppr3Teqo="
      before_install:
        - curl --insecure https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.3.0.2102-macosx.zip -o sonar-scanner-cli-4.3.0.2102-macosx.zip
        - unzip sonar-scanner-cli-4.3.0.2102-macosx.zip -d ${TRAVIS_HOME}/.sonarscanner/
        - export PATH=${TRAVIS_HOME}/.sonarscanner/sonar-scanner-4.3.0.2102-macosx/bin:$PATH
      before_script:
        - export CXX=clang++
      script:
        - build-wrapper-macosx-x86 --out-dir bw-output make -j2 -C samples/
        - sonar-scanner -D sonar.projectKey=HTTPRequestMacOS -D sonar.projectName="HTTPRequest macOS" -D sonar.cfamily.threads=2 || true
