trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-latest'
  steps:
  - script: |
      cd example
      make -j2
    displayName: 'make'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: MSBuild@1
    inputs:
      solution: example/example.vcxproj
      configuration: Release

- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      cd example
      make -j2
    displayName: 'make'
