version: 2

jobs:
  test:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: git submodule update --init
      - run: make -C tests/
      - run: tests/tests
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  version: 2
  dist-compile:
    jobs:
      - test:
          context: SonarCloud