version: 2.1

jobs:
  test:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: git submodule update --init
      - run: build-wrapper --out-dir bw-output make -C tests/
      - run: tests/tests
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - test:
          context: SonarCloud