version: 2.1

jobs:
  test:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: git submodule update --init
      - run:
          name: Download SonarCloud
          command: |
            apt update && apt install -y curl
            wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
            unzip build-wrapper-linux-x86.zip
            cp build-wrapper-linux-x86/libinterceptor-x86_64.so build-wrapper-linux-x86/libinterceptor-haswell.so
      - run:
          name: Build and run
          command: |
            ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output make -C tests/
            tests/tests
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - test:
          context: SonarCloud